# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/smi/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/motorola/smi/proprietary/bin/akmd8963:system/bin/akmd8963 \
	vendor/motorola/smi/proprietary/bin/bd_prov:system/bin/bd_prov \
	vendor/motorola/smi/proprietary/etc/firmware/vpimg_es305b-BB.bin:system/etc/firmware/vpimg_es305b-BB.bin \
	vendor/motorola/smi/proprietary/etc/firmware/vpimg_es305b-NH.bin:system/etc/firmware/vpimg_es305b-NH.bin \
	vendor/motorola/smi/proprietary/etc/firmware/vpimg_es305b.bin:system/etc/firmware/vpimg_es305b.bin \
	vendor/motorola/smi/proprietary/etc/parameter-framework/ParameterFrameworkConfiguration.xml:system/etc/parameter-framework/ParameterFrameworkConfiguration.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Audio/AudienceSubsystem.xml:system/etc/parameter-framework/Structure/Audio/AudienceSubsystem.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Audio/AudioClass.xml:system/etc/parameter-framework/Structure/Audio/AudioClass.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Audio/ConfigurationSubsystem.xml:system/etc/parameter-framework/Structure/Audio/ConfigurationSubsystem.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Audio/IMCSubsystem.xml:system/etc/parameter-framework/Structure/Audio/IMCSubsystem.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Audio/LPESubsystem.xml:system/etc/parameter-framework/Structure/Audio/LPESubsystem.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Audio/MSICSubsystem.xml:system/etc/parameter-framework/Structure/Audio/MSICSubsystem.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Audio/SysfsPmdownTimeMDFLDSubsystem.xml:system/etc/parameter-framework/Structure/Audio/SysfsPmdownTimeMDFLDSubsystem.xml \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_bt_carkit_csv_nb.bin:system/etc/phonecall_es305b_bt_carkit_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_bt_carkit_csv_wb.bin:system/etc/phonecall_es305b_bt_carkit_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_bt_carkit_voip_nb.bin:system/etc/phonecall_es305b_bt_carkit_voip_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_bt_carkit_voip_wb.bin:system/etc/phonecall_es305b_bt_carkit_voip_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_bt_hsp_csv_nb.bin:system/etc/phonecall_es305b_bt_hsp_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_bt_hsp_csv_wb.bin:system/etc/phonecall_es305b_bt_hsp_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_bt_hsp_voip_nb.bin:system/etc/phonecall_es305b_bt_hsp_voip_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_bt_hsp_voip_wb.bin:system/etc/phonecall_es305b_bt_hsp_voip_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_csv_nb.bin:system/etc/phonecall_es305b_close_talk_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_csv_wb.bin:system/etc/phonecall_es305b_close_talk_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_hac_csv_nb.bin:system/etc/phonecall_es305b_close_talk_hac_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_hac_csv_wb.bin:system/etc/phonecall_es305b_close_talk_hac_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_hac_voip_nb.bin:system/etc/phonecall_es305b_close_talk_hac_voip_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_hac_voip_wb.bin:system/etc/phonecall_es305b_close_talk_hac_voip_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_tty_hco_csv_nb.bin:system/etc/phonecall_es305b_close_talk_tty_hco_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_tty_hco_csv_wb.bin:system/etc/phonecall_es305b_close_talk_tty_hco_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_tty_hco_hac_csv_nb.bin:system/etc/phonecall_es305b_close_talk_tty_hco_hac_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_tty_hco_hac_csv_wb.bin:system/etc/phonecall_es305b_close_talk_tty_hco_hac_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_tty_vco_csv_nb.bin:system/etc/phonecall_es305b_close_talk_tty_vco_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_tty_vco_csv_wb.bin:system/etc/phonecall_es305b_close_talk_tty_vco_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_voip_nb.bin:system/etc/phonecall_es305b_close_talk_voip_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_close_talk_voip_wb.bin:system/etc/phonecall_es305b_close_talk_voip_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headphone_close_talk_csv_nb.bin:system/etc/phonecall_es305b_headphone_close_talk_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headphone_close_talk_csv_wb.bin:system/etc/phonecall_es305b_headphone_close_talk_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headphone_close_talk_voip_nb.bin:system/etc/phonecall_es305b_headphone_close_talk_voip_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headphone_close_talk_voip_wb.bin:system/etc/phonecall_es305b_headphone_close_talk_voip_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headset_close_talk_csv_nb.bin:system/etc/phonecall_es305b_headset_close_talk_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headset_close_talk_csv_wb.bin:system/etc/phonecall_es305b_headset_close_talk_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headset_close_talk_voip_nb.bin:system/etc/phonecall_es305b_headset_close_talk_voip_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headset_close_talk_voip_wb.bin:system/etc/phonecall_es305b_headset_close_talk_voip_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headset_tty_full_csv_nb.bin:system/etc/phonecall_es305b_headset_tty_full_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_headset_tty_full_csv_wb.bin:system/etc/phonecall_es305b_headset_tty_full_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_no_acoustic_csv_nb.bin:system/etc/phonecall_es305b_no_acoustic_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_no_acoustic_csv_wb.bin:system/etc/phonecall_es305b_no_acoustic_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_no_acoustic_voip_nb.bin:system/etc/phonecall_es305b_no_acoustic_voip_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_no_acoustic_voip_wb.bin:system/etc/phonecall_es305b_no_acoustic_voip_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_speaker_far_talk_csv_nb.bin:system/etc/phonecall_es305b_speaker_far_talk_csv_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_speaker_far_talk_csv_wb.bin:system/etc/phonecall_es305b_speaker_far_talk_csv_wb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_speaker_far_talk_voip_nb.bin:system/etc/phonecall_es305b_speaker_far_talk_voip_nb.bin \
	vendor/motorola/smi/proprietary/etc/phonecall_es305b_speaker_far_talk_voip_wb.bin:system/etc/phonecall_es305b_speaker_far_talk_voip_wb.bin \
	vendor/motorola/smi/proprietary/lib/hw/audio.primary.vendor.smi.so:system/lib/hw/audio.primary.vendor.smi.so \
	vendor/motorola/smi/proprietary/lib/hw/audio_policy.smi.so:system/lib/hw/audio_policy.smi.so \
	vendor/motorola/smi/proprietary/lib/libaudience-manager.so:system/lib/libaudience-manager.so \
	vendor/motorola/smi/proprietary/lib/libaudiohalutils.so:system/lib/libaudiohalutils.so \
	vendor/motorola/smi/proprietary/lib/libaudioresample.so:system/lib/libaudioresample.so \
	vendor/motorola/smi/proprietary/lib/libevent-listener.so:system/lib/libevent-listener.so \
	vendor/motorola/smi/proprietary/lib/libinterface-provider-lib.so:system/lib/libinterface-provider-lib.so \
	vendor/motorola/smi/proprietary/lib/libinterface-provider.so:system/lib/libinterface-provider.so \
	vendor/motorola/smi/proprietary/lib/libmamgr-xmm.so:system/lib/libmamgr-xmm.so \
	vendor/motorola/smi/proprietary/lib/libparameter.so:system/lib/libparameter.so \
	vendor/motorola/smi/proprietary/lib/libproperty.so:system/lib/libproperty.so \
	vendor/motorola/smi/proprietary/lib/parameter-framework-plugins/Audio/libaudience-subsystem.so:system/lib/parameter-framework-plugins/Audio/libaudience-subsystem.so \
	vendor/motorola/smi/proprietary/lib/parameter-framework-plugins/Audio/libimc-subsystem.so:system/lib/parameter-framework-plugins/Audio/libimc-subsystem.so \
	vendor/motorola/smi/proprietary/lib/parameter-framework-plugins/Audio/liblpe-subsystem.so:system/lib/parameter-framework-plugins/Audio/liblpe-subsystem.so \
	vendor/motorola/smi/proprietary/lib/parameter-framework-plugins/Audio/libtinyalsactl-subsystem.so:system/lib/parameter-framework-plugins/Audio/libtinyalsactl-subsystem.so \
	vendor/motorola/smi/proprietary/lib/parameter-framework-plugins/Audio/libtinyamixer-subsystem.so:system/lib/parameter-framework-plugins/Audio/libtinyamixer-subsystem.so \
	vendor/motorola/smi/proprietary/lib/parameter-framework-plugins/System/libproperty-subsystem.so:system/lib/parameter-framework-plugins/System/libproperty-subsystem.so \
	vendor/motorola/smi/proprietary/etc/firmware/aac_dec_1.bin:system/etc/firmware/aac_dec_1.bin \
	vendor/motorola/smi/proprietary/etc/firmware/aac_enc_1.bin:system/etc/firmware/aac_enc_1.bin \
	vendor/motorola/smi/proprietary/etc/firmware/aac_v1_dec_1.bin:system/etc/firmware/aac_v1_dec_1.bin \
	vendor/motorola/smi/proprietary/etc/firmware/aac_v2_dec_1.bin:system/etc/firmware/aac_v2_dec_1.bin \
	vendor/motorola/smi/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
	vendor/motorola/smi/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd \
	vendor/motorola/smi/proprietary/etc/firmware/mp3_dec_1.bin:system/etc/firmware/mp3_dec_1.bin \
	vendor/motorola/smi/proprietary/etc/firmware/wma9_dec_1.bin:system/etc/firmware/wma9_dec_1.bin \
	vendor/motorola/smi/proprietary/lib/hw/hwcomposer.smi.so:system/lib/hw/hwcomposer.smi.so \
	vendor/motorola/smi/proprietary/lib/libpvr2d.so:system/lib/libpvr2d.so \
	vendor/motorola/smi/proprietary/lib/libwbxmlparser.so:system/lib/libwbxmlparser.so \
	vendor/motorola/smi/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	vendor/motorola/smi/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX540_121.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_121.so \
	vendor/motorola/smi/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_121.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_121.so \
	vendor/motorola/smi/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX540_121.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_121.so \
	vendor/motorola/smi/proprietary/vendor/lib/hw/gralloc.smi.so:system/vendor/lib/hw/gralloc.smi.so \
	vendor/motorola/smi/proprietary/vendor/lib/hw/memtrack.smi.so:system/vendor/lib/hw/memtrack.smi.so \
	vendor/motorola/smi/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
	vendor/motorola/smi/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
	vendor/motorola/smi/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
	vendor/motorola/smi/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
	vendor/motorola/smi/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
	vendor/motorola/smi/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
	vendor/motorola/smi/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
	vendor/motorola/smi/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
	vendor/motorola/smi/proprietary/lib/hw/camera.vendor.sc1.so:system/lib/hw/camera.vendor.sc1.so \
	vendor/motorola/smi/proprietary/lib/libmfldadvci.so:system/lib/libmfldadvci.so \
	vendor/motorola/smi/proprietary/lib/libSh3aParamsLiteOn8M.so:system/lib/libSh3aParamsLiteOn8M.so \
	vendor/motorola/smi/proprietary/lib/libSh3aParamsSemcoLc898211.so:system/lib/libSh3aParamsSemcoLc898211.so \
	vendor/motorola/smi/proprietary/lib/libVdlFaceDetection.so:system/lib/libVdlFaceDetection.so \
	vendor/motorola/smi/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin \
	vendor/motorola/smi/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin \
	vendor/motorola/smi/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin \
	vendor/motorola/smi/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin \
	vendor/motorola/smi/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin \
	vendor/motorola/smi/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin \
	vendor/motorola/smi/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin \
	vendor/motorola/smi/proprietary/bin/gkisystem:system/bin/gkisystem \
	vendor/motorola/smi/proprietary/bin/gps_driver:system/bin/gps_driver \
	vendor/motorola/smi/proprietary/bin/location:system/bin/location \
	vendor/motorola/smi/proprietary/bin/TIDrv:system/bin/TIDrv \
	vendor/motorola/smi/proprietary/etc/gps.conf:system/etc/gps.conf \
	vendor/motorola/smi/proprietary/etc/gps/ti/GPSCConfigFile.cfg:system/etc/gps/ti/GPSCConfigFile.cfg \
	vendor/motorola/smi/proprietary/etc/gps/ti/patch-X.0.ce:system/etc/gps/ti/patch-X.0.ce \
	vendor/motorola/smi/proprietary/etc/gps/ti/pathconfigfile.txt:system/etc/gps/ti/pathconfigfile.txt \
	vendor/motorola/smi/proprietary/etc/location.cfg:system/etc/location.cfg \
	vendor/motorola/smi/proprietary/lib/hw/gps.smi.so:system/lib/hw/gps.smi.so \
	vendor/motorola/smi/proprietary/lib/libgki.so:system/lib/libgki.so \
	vendor/motorola/smi/proprietary/lib/libgpsTI.so:system/lib/libgpsTI.so \
	vendor/motorola/smi/proprietary/lib/libmcphal.so:system/lib/libmcphal.so \
	vendor/motorola/smi/proprietary/lib/libmcphalgps.so:system/lib/libmcphalgps.so \
	vendor/motorola/smi/proprietary/lib/libmotodbgutils.so:system/lib/libmotodbgutils.so \
	vendor/motorola/smi/proprietary/lib/libtinyxml_stl.so:system/lib/libtinyxml_stl.so \
	vendor/motorola/smi/proprietary/bin/mmgr:system/bin/mmgr \
	vendor/motorola/smi/proprietary/etc/firmware/fw_sst_082f.bin:system/etc/firmware/fw_sst_082f.bin \
	vendor/motorola/smi/proprietary/etc/firmware/fw_sst_08e7.bin:system/etc/firmware/fw_sst_08e7.bin \
	vendor/motorola/smi/proprietary/etc/telephony/mmgr.conf:system/etc/telephony/mmgr.conf \
	vendor/motorola/smi/proprietary/lib/libglib-2.0.so:system/lib/libglib-2.0.so \
	vendor/motorola/smi/proprietary/lib/libmmgrcli.so:system/lib/libmmgrcli.so \
	vendor/motorola/smi/proprietary/lib/libpn544_fw.bak:system/lib/libpn544_fw.bak \
	vendor/motorola/smi/proprietary/lib/libsecurity_api.so:system/lib/libsecurity_api.so \
	vendor/motorola/smi/proprietary/lib/parameter-framework-plugins/Fs/libfs-subsystem.so:system/lib/parameter-framework-plugins/Fs/libfs-subsystem.so \
	vendor/motorola/smi/proprietary/lib/hw/sensors.smi.so:system/lib/hw/sensors.smi.so \
	vendor/motorola/smi/proprietary/etc/thermal_sensor_config.xml:system/etc/thermal_sensor_config.xml \
	vendor/motorola/smi/proprietary/etc/thermal_throttle_config.xml:system/etc/thermal_throttle_config.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/ParameterFrameworkConfigurationVibrator.xml:system/etc/parameter-framework/ParameterFrameworkConfigurationVibrator.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Settings/Vibrator/VibratorConfigurableDomains.xml:system/etc/parameter-framework/Settings/Vibrator/VibratorConfigurableDomains.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Vibrator/AlsaVibratorClass.xml:system/etc/parameter-framework/Structure/Vibrator/AlsaVibratorClass.xml \
	vendor/motorola/smi/proprietary/etc/parameter-framework/Structure/Vibrator/AlsaVibratorSubsystem.xml:system/etc/parameter-framework/Structure/Vibrator/AlsaVibratorSubsystem.xml \
	vendor/motorola/smi/proprietary/lib/hw/vibrator.vendor.smi.so:system/lib/hw/vibrator.vendor.smi.so \
	vendor/motorola/smi/proprietary/etc/firmware/TIInit_10.5.20.bts:system/etc/firmware/TIInit_10.5.20.bts \
	vendor/motorola/smi/proprietary/etc/firmware/TIInit_10.6.15.bts:system/etc/firmware/TIInit_10.6.15.bts \
	vendor/motorola/smi/proprietary/etc/firmware/atmxt-r1.tdat:system/etc/firmware/atmxt-r1.tdat \
	vendor/motorola/smi/proprietary/etc/firmware/atmxt-r2.tdat:system/etc/firmware/atmxt-r2.tdat \
	vendor/motorola/smi/proprietary/etc/atomisp/CGamma_DIS5MP.bin:system/etc/atomisp/CGamma_DIS5MP.bin \
	vendor/motorola/smi/proprietary/etc/atomisp/Mor_14MP_8BQ.txt:system/etc/atomisp/Mor_14MP_8BQ.txt \
	vendor/motorola/smi/proprietary/etc/atomisp/Mor_8MP_8BQ.txt:system/etc/atomisp/Mor_8MP_8BQ.txt \
	vendor/motorola/smi/proprietary/etc/atomisp/noise.fpn:system/etc/atomisp/noise.fpn \
	vendor/motorola/smi/proprietary/etc/atomisp/Preview_UserParameter_AbicoFI86A086.prm:system/etc/atomisp/Preview_UserParameter_AbicoFI86A086.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Preview_UserParameter_DIS14M.prm:system/etc/atomisp/Preview_UserParameter_DIS14M.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Preview_UserParameter_LiteOn8M.prm:system/etc/atomisp/Preview_UserParameter_LiteOn8M.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Preview_UserParameter_SemcoLc898211.prm:system/etc/atomisp/Preview_UserParameter_SemcoLc898211.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Primary_UserParameter_AbicoFI86A086.prm:system/etc/atomisp/Primary_UserParameter_AbicoFI86A086.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Primary_UserParameter_DIS14M.prm:system/etc/atomisp/Primary_UserParameter_DIS14M.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Primary_UserParameter_LiteOn8M.prm:system/etc/atomisp/Primary_UserParameter_LiteOn8M.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Primary_UserParameter_SemcoLc898211.prm:system/etc/atomisp/Primary_UserParameter_SemcoLc898211.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Video_UserParameter_AbicoFI86A086.prm:system/etc/atomisp/Video_UserParameter_AbicoFI86A086.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Video_UserParameter_DIS14M.prm:system/etc/atomisp/Video_UserParameter_DIS14M.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Video_UserParameter_LiteOn8M.prm:system/etc/atomisp/Video_UserParameter_LiteOn8M.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/Video_UserParameter_SemcoLc898211.prm:system/etc/atomisp/Video_UserParameter_SemcoLc898211.prm \
	vendor/motorola/smi/proprietary/etc/atomisp/YGamma_DIS5MP.bin:system/etc/atomisp/YGamma_DIS5MP.bin \
	vendor/motorola/smi/proprietary/etc/firmware/isp_acc_deghosting.bin:system/etc/firmware/isp_acc_deghosting.bin \
	vendor/motorola/smi/proprietary/etc/firmware/isp_acc_fusion.bin:system/etc/firmware/isp_acc_fusion.bin \
	vendor/motorola/smi/proprietary/etc/firmware/isp_acc_multires.bin:system/etc/firmware/isp_acc_multires.bin \
	vendor/motorola/smi/proprietary/etc/firmware/isp_acc_postproc.bin:system/etc/firmware/isp_acc_postproc.bin \
	vendor/motorola/smi/proprietary/etc/firmware/isp_acc_warp_deghost.bin:system/etc/firmware/isp_acc_warp_deghost.bin \
	vendor/motorola/smi/proprietary/etc/firmware/isp_acc_warping.bin:system/etc/firmware/isp_acc_warping.bin \
	vendor/motorola/smi/proprietary/etc/firmware/shisp.bin:system/etc/firmware/shisp.bin \
	vendor/motorola/smi/proprietary/etc/firmware/fa_extension.bin:system/etc/firmware/fa_extension.bin \
	vendor/motorola/smi/proprietary/bin/batt_health:system/bin/batt_health
